[package]
name = "clip_notify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = {version = "1.1.1", features = ["xfixes"]}
kira = {version = "0.6.0", features = ["mp3"]}